// Real-browser driver for the Home Agent "LAN chat" served page. It loads the
// served page in an actual browser and drives its own JavaScript — the login form,
// the `EventSource('/api/events')` subscription, the `#send` handler POSTing
// `/api/chat`, and the reply/media rendering. That is the "I typed something in the
// browser and nothing happened" surface, exercised through the same Python transport
// (password login → session cookie → SSE) a LAN browser would use.
//
// We open the page in a fresh Electron BrowserWindow of the app under test
// rather than a separately-launched Chromium: the e2e suite only ever installs
// the Electron binary (never `npx playwright install`), so `chromium.launch()`
// isn't available — but the running app's Chromium loads the plain HTTP page
// exactly as a user's browser would (fetch + EventSource + same-origin cookies).

import { type ElectronApplication, type Page, expect } from '@playwright/test'

/** Open the served page in a new BrowserWindow and sign in through the real DOM.
 *  Resolves with the window's Page once the chat screen is up and the SSE stream
 *  reports connected. */
export async function openLocalWebChat(
  electronApp: ElectronApplication,
  baseUrl: string,
  password: string,
): Promise<Page> {
  const pagePromise = electronApp.waitForEvent('window')
  await electronApp.evaluate(async ({ BrowserWindow }, url) => {
    const win = new BrowserWindow({
      width: 480,
      height: 820,
      // Keep timers/EventSource running even if the window isn't focused, so the
      // SSE reply isn't throttled while the test drives the main window.
      webPreferences: { backgroundThrottling: false },
    })
    await win.loadURL(url)
  }, baseUrl)

  const page = await pagePromise
  page.on('pageerror', (err) => console.error(`[local-web page:error] ${err.message}`))
  await signInAndAwaitChat(page, password)
  return page
}

/**
 * Sign in (when the login form is showing) and wait until the chat screen is live,
 * then arm the prompt auto-confirm handler. Split from `openLocalWebChat` so the
 * page can also be driven without standing up the whole Electron app.
 */
export async function signInAndAwaitChat(page: Page, password: string): Promise<void> {
  // The page settles on one of two screens: the login form (fresh) or straight
  // to chat when a prior window's session cookie still authenticates (Electron
  // BrowserWindows share the default session). Both screens are always in the
  // DOM (one is hidden), so wait for whichever became visible — a locator
  // matching both would be a strict-mode violation.
  const passwordField = page.getByLabel('Password')
  await expect
    .poll(async () => (await passwordField.isVisible()) || (await composer(page).isVisible()), {
      timeout: 15_000,
    })
    .toBe(true)

  // Only sign in when the login form is actually showing.
  if (await passwordField.isVisible()) {
    await passwordField.fill(password)
    await page.getByRole('button', { name: 'Sign in' }).click()
  }

  // A live session swaps to the chat screen and opens the SSE stream, which posts
  // the "Connected" system line. Failure here means the page JS never
  // established the session/stream — exactly the silent break we're guarding.
  await expect(composer(page)).toBeVisible({ timeout: 15_000 })
  await expect(page.getByText('Connected', { exact: false })).toBeVisible({ timeout: 15_000 })

  // Auto-confirm any in-channel prompt that appears mid-turn (e.g. a model-
  // download approval renders as a button group) so a turn that needs one still
  // completes — the DOM analogue of a user tapping "Confirm". Registered once per
  // page rather than per send so handlers don't stack. The page retires a prompt's
  // buttons once tapped, which is also what lets Playwright's post-handler
  // "overlay is gone" check pass.
  await page.addLocatorHandler(promptButtons(page).first(), async (btn) => {
    await btn.click()
  })
}

const composer = (page: Page) => page.getByRole('textbox', { name: 'Message' })

/** Buttons of any interactive prompt still awaiting an answer. */
const promptButtons = (page: Page) =>
  page.getByRole('group', { name: 'Choose an option' }).getByRole('button')

/** Settled bot replies. The in-flight draft and the typing placeholder carry
 *  different accessible names, so this counts only finished messages. */
function settledBotBubbles(page: Page) {
  return page.getByRole('article', { name: 'Home Agent response', exact: true })
}

/** Messages the user sent, optionally filtered to those containing `text`. */
export function userMessages(page: Page, text?: string) {
  const messages = page.getByRole('article', { name: 'Your message', exact: true })
  return text ? messages.filter({ hasText: text }) : messages
}

/** Images generated by the agent and rendered inline in the log (bot `photo` events). */
export function lanImages(page: Page) {
  return page.locator('#log img.inline')
}

/** Videos generated by the agent and rendered inline in the log (bot `video` events). */
export function lanVideos(page: Page) {
  return page.locator('#log video.inline')
}

/** Type into the composer and click send. Fire-and-forget: the caller decides
 *  what to await (a reply, a repaint, a specific bubble). */
export async function sendMessage(page: Page, text: string): Promise<void> {
  await composer(page).fill(text)
  await page.getByRole('button', { name: 'Send' }).click()
}

/**
 * Send a message/command and resolve once a *new* settled reply has rendered. Waits on
 * the (before+1)th "Home Agent response" via a web-first assertion — deliberately NOT a
 * bare `.count()` poll: a settled response only appears after the reply finished
 * streaming (the live draft carries a different name), and a web-first assertion is what
 * lets Playwright run the `addLocatorHandler` auto-confirm mid-wait. A `.count()` poll
 * would never trigger it, so a turn that puts up a keyboard (a tool step, a model-
 * download approval) would stall forever waiting on a tap that never happens.
 *
 * Only for turns that leave the log intact: a command that repaints the page
 * (`/new`, `/load`) resets the count, so use {@link sendAndAwaitText} there.
 */
export async function sendAndAwaitReply(
  page: Page,
  text: string,
  timeoutMs: number,
): Promise<string> {
  const settled = settledBotBubbles(page)
  const before = await settled.count()
  await sendMessage(page, text)
  await expect(settled.nth(before)).toBeVisible({ timeout: timeoutMs })
  return ((await settled.last().innerText()) ?? '').trim()
}

/** Which kind of generated media a turn is expected to render inline. */
export type MediaKind = 'image' | 'video'

/**
 * The channel's marker for a tool the adapter doesn't render specially — the media
 * tool included ("Using media…", then "Used media", or "media failed"). Built by
 * `renderGenericToolMarker`, so its presence is proof the model actually called the
 * tool rather than describing an image it never generated.
 *
 * Deliberately NOT scoped to settled bubbles. The marker spends the whole generation
 * as the live draft and is only finalized into a "Home Agent response" once the turn
 * produces its next text — which for a video is many minutes later, i.e. precisely the
 * wait this is meant to license. `finalizeBot` re-labels the same element in place, so
 * a locator matching both names follows the marker across that transition instead of
 * seeing it disappear and reappear.
 */
function mediaToolMarkers(page: Page) {
  return page
    .getByRole('article', { name: /^Home Agent (response|draft)$/ })
    .filter({ hasText: /(?:Using|Used) media|media failed/ })
}

/**
 * Send an agentic prompt that should make the Home Agent generate media, and resolve
 * once a *new* inline `<img>`/`<video>` has rendered in the served log. Any in-channel
 * model-download prompt is auto-confirmed by the handler registered in openLocalWebChat,
 * so a first-time generation that pulls a model still completes (it just takes as long
 * as the download). Throws if no new media appears.
 *
 * Split into "did it call the tool" and "did the tool produce something", because the
 * two failures need different verdicts. A model that answers in prose without ever
 * invoking its media tool — "Here's a fresh take on your lizard!", no tool call, no
 * image — is a different bug from a generation that is simply slow, and a single wait
 * reports both as "no image after eight minutes".
 *
 * What this deliberately does NOT do is treat a settled reply as the end of the turn.
 * The served page names every bot bubble "Home Agent response": the tool marker, the
 * media, and the prose all qualify, and the model routinely narrates *before* calling
 * the tool. So a turn produces several, in no fixed order, and "a reply arrived" says
 * nothing about whether the turn is over. There is no reliable DOM idle signal either
 * — `hideTyping()` fires on every bubble append, so the indicator is down for most of
 * a long generation.
 */
export async function sendAndAwaitMedia(
  page: Page,
  prompt: string,
  kind: MediaKind,
  timeoutMs: number,
): Promise<void> {
  const media = kind === 'image' ? lanImages(page) : lanVideos(page)
  const markers = mediaToolMarkers(page)
  const settled = settledBotBubbles(page)
  const before = await media.count()
  const markersBefore = await markers.count()
  await sendMessage(page, prompt)

  // Web-first assertions throughout (never a `.count()` poll) so Playwright runs the
  // `addLocatorHandler` auto-confirm mid-wait — a first-time generation gates on an
  // in-channel model-download approval, which a bare count poll would never tap.

  // The tool starting, or the media itself for a generation quick enough to beat the
  // marker. Same ceiling as the wait it replaces, so nothing that used to pass can now
  // time out early — this only changes what a failure says.
  try {
    await expect(media.nth(before).or(markers.nth(markersBefore)).first()).toBeVisible({
      timeout: timeoutMs,
    })
  } catch {
    // Read the reply here rather than passing it as the assertion's message: the
    // message is built when the assertion is *set up*, which is before the turn has
    // said anything, so it would quote whatever the previous turn left behind.
    const reply = (
      await settled
        .last()
        .innerText()
        .catch(() => '')
    )
      .trim()
      .slice(0, 300)
    throw new Error(
      `the Home Agent never invoked its media tool for a ${kind} generation — it likely ` +
        `answered in prose instead. Its last reply was: "${reply}"`,
    )
  }

  // The tool is running, so the generation gets a full budget of its own: a video on a
  // laptop GPU takes many minutes, and cutting that short is what turned a working run
  // into a failure.
  await expect(
    media.nth(before),
    `the Home Agent invoked its media tool but rendered no new inline ${kind}`,
  ).toBeVisible({ timeout: timeoutMs })
}

/**
 * Send a message/command and resolve once a settled reply containing `expected`
 * is on screen. Counting bubbles cannot work for the commands that repaint the
 * log from a conversation transcript, because the repaint drops the earlier
 * replies — so match the reply itself instead.
 */
export async function sendAndAwaitText(
  page: Page,
  text: string,
  expected: string,
  timeoutMs: number,
): Promise<void> {
  await sendMessage(page, text)
  await expect(settledBotBubbles(page).filter({ hasText: expected })).toHaveCount(1, {
    timeout: timeoutMs,
  })
}
