import { describe, expect, it } from 'vitest'
import type { UIMessage } from 'ai'
import type { MediaItem } from '@/assets/js/store/imageGenerationPresets'
import {
  collectToolMediaUrls,
  conversationMode,
  conversationTimes,
  conversationTitle,
  entryHaystack,
  entryRuntimeShown,
  isEmptyDraft,
  matchesFilter,
  mediaTimes,
  mediaTitle,
  mediaSettings,
  searchEntries,
  sortEntries,
  type AgentEntry,
  type ConversationEntry,
  type HistoryEntry,
  type MediaEntry,
} from '@/assets/js/store/historyEntries'

// The rules the one history window runs on: which rows a filter lists, what a
// row is named, and that an image generated by a chat tool is not listed twice.

const userTurn = (text: string, timestamp?: number): UIMessage =>
  ({
    id: `u-${text}`,
    role: 'user',
    parts: [{ type: 'text', text }],
    ...(timestamp ? { metadata: { timestamp } } : {}),
  }) as UIMessage

const comfyTurn = (url: string): UIMessage =>
  ({
    id: `a-${url}`,
    role: 'assistant',
    parts: [
      {
        type: 'tool-comfyUI',
        state: 'output-available',
        output: { images: [{ type: 'image', imageUrl: url }] },
      },
    ],
  }) as unknown as UIMessage

function conversation(overrides: Partial<ConversationEntry> = {}): ConversationEntry {
  return {
    kind: 'conversation',
    id: '1000',
    title: 'a haiku about ports',
    mode: 'chat',
    threadKind: 'main',
    presetName: 'Assistant',
    createdAt: 1_000,
    updatedAt: 2_000,
    messages: [userTurn('a haiku about ports')],
    ...overrides,
  }
}

function agent(overrides: Partial<AgentEntry> = {}): AgentEntry {
  return {
    kind: 'agent',
    id: 'aipg-agent-1',
    title: 'dodge asteroids',
    mode: 'agent',
    presetName: 'Game Agent',
    workspaceDir: '/games/space-dodger',
    createdAt: 1_000,
    updatedAt: 3_000,
    messages: [userTurn('dodge asteroids')],
    ...overrides,
  }
}

function mediaItem(overrides: Partial<MediaItem> = {}): MediaItem {
  return {
    id: 'm1',
    type: 'image',
    state: 'done',
    mode: 'imageGen',
    imageUrl: 'aipg-media://AIPG_00001_.png',
    settings: { prompt: 'a red bicycle', preset: 'Line Art' },
    createdAt: 4_000,
    ...overrides,
  } as MediaItem
}

function media(overrides: Partial<MediaEntry> = {}): MediaEntry {
  const item = overrides.media ?? mediaItem()
  return {
    kind: 'media',
    id: item.id,
    title: mediaTitle(item),
    mode: item.mode,
    presetName: mediaSettings(item).preset,
    origin: 'canvas',
    createdAt: 4_000,
    updatedAt: 4_000,
    ...overrides,
    media: item,
  }
}

describe('conversationMode', () => {
  it('keeps audio presets in audio mode and everything else in chat', () => {
    expect(conversationMode('audio')).toBe('audio')
    expect(conversationMode('chat')).toBe('chat')
    expect(conversationMode(null)).toBe('chat')
    // An agent preset cannot own a transcript row — that is its own kind.
    expect(conversationMode('agent')).toBe('chat')
  })
})

describe('conversationTitle', () => {
  it('prefers the title the user set', () => {
    const messages = [
      { ...userTurn('first prompt'), metadata: { conversationTitle: 'Renamed' } } as UIMessage,
    ]
    expect(conversationTitle(messages)).toBe('Renamed')
  })

  it('falls back to the first prompt, then to a placeholder', () => {
    expect(conversationTitle([userTurn('write me a poem')])).toBe('write me a poem')
    expect(conversationTitle([])).toBe('New Conversation')
  })
})

describe('conversationTimes', () => {
  it('reads creation off the key and activity off the last message', () => {
    expect(
      conversationTimes('1700000000000', [userTurn('hi'), userTurn('again', 1_800_000)]),
    ).toEqual({ createdAt: 1_700_000_000_000, updatedAt: 1_700_000_000_000 })
    expect(conversationTimes('1000', [userTurn('hi'), userTurn('again', 5_000)])).toEqual({
      createdAt: 1_000,
      updatedAt: 5_000,
    })
  })

  it('survives the legacy Home Agent key, which is not a timestamp', () => {
    expect(conversationTimes('__aipg_home_agent__', [])).toEqual({ createdAt: 0, updatedAt: 0 })
  })
})

describe('mediaTitle', () => {
  it('names a run after its prompt, or its preset when there is none', () => {
    expect(mediaTitle(mediaItem())).toBe('a red bicycle')
    expect(mediaTitle(mediaItem({ settings: { preset: 'Image To 3D Model' } }))).toBe(
      'Image To 3D Model',
    )
    expect(mediaTitle(mediaItem({ settings: {} }))).toBe('Untitled')
  })

  it('survives an item persisted before it carried settings', () => {
    const legacy = mediaItem()
    delete (legacy as { settings?: unknown }).settings
    expect(mediaTitle(legacy)).toBe('Untitled')
    expect(entryHaystack(media({ media: legacy }))).toContain('untitled')
  })
})

describe('mediaTimes', () => {
  it('puts a run still in flight at the top', () => {
    const started = mediaItem({ state: 'generating', createdAt: undefined })
    expect(mediaTimes(started, 9_000)).toEqual({ createdAt: 9_000, updatedAt: 9_000 })
    expect(mediaTimes(mediaItem(), 9_000)).toEqual({ createdAt: 4_000, updatedAt: 4_000 })
  })
})

describe('collectToolMediaUrls', () => {
  it('finds what a transcript already shows', () => {
    const urls = collectToolMediaUrls([
      [userTurn('draw a cover'), comfyTurn('aipg-media://AIPG_00007_.png')],
      [userTurn('nothing here')],
    ])
    expect([...urls]).toEqual(['aipg-media://AIPG_00007_.png'])
  })
})

describe('matchesFilter', () => {
  const current = (entry: HistoryEntry, currentMode: ModeType, agentPresetName = '') =>
    matchesFilter(entry, { filter: 'current', currentMode, agentPresetName })

  it('lists only the current mode, and never a Home Agent thread', () => {
    expect(current(conversation(), 'chat')).toBe(true)
    expect(current(conversation(), 'audio')).toBe(false)
    expect(current(conversation({ mode: 'audio' }), 'audio')).toBe(true)
    expect(current(conversation({ threadKind: 'homeAgent' }), 'chat')).toBe(false)
    expect(current(media(), 'imageGen')).toBe(true)
    expect(current(media(), 'chat')).toBe(false)
    expect(current(media({ origin: 'tool' }), 'imageGen')).toBe(false)
  })

  it('keeps the games library in one agent list', () => {
    expect(current(agent(), 'agent', 'Game Agent')).toBe(true)
    expect(current(agent({ presetName: 'Quick Coder' }), 'agent', 'Game Agent')).toBe(true)
    expect(current(agent({ presetName: 'Agent' }), 'agent', 'Game Agent')).toBe(false)
    expect(current(agent(), 'chat')).toBe(false)
  })

  it('shows every kind under All, minus media a transcript already carries', () => {
    const all = (entry: HistoryEntry) =>
      matchesFilter(entry, { filter: 'all', currentMode: 'chat', agentPresetName: 'Agent' })
    expect(all(conversation({ threadKind: 'homeAgent' }))).toBe(true)
    expect(all(agent())).toBe(true)
    expect(all(media())).toBe(true)
    expect(all(media({ origin: 'tool' }))).toBe(false)
  })

  it('swaps the current-mode list for the remote one while a remote thread is open', () => {
    const remote = (entry: HistoryEntry) =>
      matchesFilter(entry, { filter: 'current', currentMode: 'chat', threadScope: 'homeAgent' })
    expect(remote(conversation({ threadKind: 'homeAgent' }))).toBe(true)
    expect(remote(conversation())).toBe(false)
    expect(remote(agent())).toBe(false)
    expect(remote(media())).toBe(false)
  })
})

describe('entryRuntimeShown', () => {
  it('marks only the kind the app is showing, so All has one active row', () => {
    expect(entryRuntimeShown(conversation(), 'chat')).toBe(true)
    expect(entryRuntimeShown(conversation(), 'audio')).toBe(true)
    expect(entryRuntimeShown(conversation(), 'imageGen')).toBe(false)
    expect(entryRuntimeShown(agent(), 'agent')).toBe(true)
    expect(entryRuntimeShown(agent(), 'chat')).toBe(false)
    expect(entryRuntimeShown(media(), 'imageGen')).toBe(true)
    expect(entryRuntimeShown(media(), 'chat')).toBe(false)
  })
})

describe('isEmptyDraft', () => {
  it('is only an unsent transcript', () => {
    expect(isEmptyDraft(conversation({ messages: [] }))).toBe(true)
    expect(isEmptyDraft(conversation())).toBe(false)
    expect(isEmptyDraft(agent({ messages: [] }))).toBe(false)
    expect(isEmptyDraft(media())).toBe(false)
  })

  it('is listed only while the app sits on it, under every filter', () => {
    const draft = conversation({ id: '2000', messages: [] })
    const context = { currentMode: 'chat' as ModeType, activeConversationId: '2000' }
    expect(matchesFilter(draft, { ...context, filter: 'current' })).toBe(true)
    expect(matchesFilter(draft, { ...context, filter: 'all' })).toBe(true)
    expect(matchesFilter(draft, { filter: 'current', currentMode: 'chat' })).toBe(false)
    expect(matchesFilter(draft, { filter: 'all', currentMode: 'chat' })).toBe(false)
    // A remote bucket nobody wrote to is hidden on the same terms.
    const remote = conversation({ id: '3000', threadKind: 'homeAgent', messages: [] })
    expect(matchesFilter(remote, { filter: 'all', currentMode: 'chat' })).toBe(false)
    expect(
      matchesFilter(remote, { filter: 'all', currentMode: 'chat', activeConversationId: '3000' }),
    ).toBe(true)
  })
})

describe('searchEntries', () => {
  const entries = [conversation(), agent(), media()]

  it('matches title, preset, prompt and the first thing the user said', () => {
    expect(searchEntries(entries, 'haiku').map((entry) => entry.id)).toEqual(['1000'])
    expect(searchEntries(entries, 'space-dodger').map((entry) => entry.id)).toEqual([
      'aipg-agent-1',
    ])
    expect(searchEntries(entries, 'bicycle').map((entry) => entry.id)).toEqual(['m1'])
    expect(searchEntries(entries, 'GAME agent').map((entry) => entry.id)).toEqual(['aipg-agent-1'])
  })

  it('returns everything for an empty query', () => {
    expect(searchEntries(entries, '   ')).toHaveLength(3)
  })

  it('reads a transcript beyond its title', () => {
    const entry = conversation({ title: 'Renamed', messages: [userTurn('port forwarding')] })
    expect(entryHaystack(entry)).toContain('port forwarding')
    expect(searchEntries([entry], 'port forwarding')).toHaveLength(1)
  })
})

describe('sortEntries', () => {
  it('puts the most recent work first', () => {
    const sorted = sortEntries([conversation(), agent(), media()])
    expect(sorted.map((entry) => entry.id)).toEqual(['m1', 'aipg-agent-1', '1000'])
  })

  it('does not mutate its input', () => {
    const entries = [conversation(), media()]
    sortEntries(entries)
    expect(entries.map((entry) => entry.id)).toEqual(['1000', 'm1'])
  })
})
